version: "3.7"
services:
  postgres:
    image: postgres:10.5
    restart: always
    container_name: pizza_show
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pizza_show
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
